import { Placeholder } from "@angular/compiler/src/i18n/i18n_ast";

const tsv_str = `	Name	NameCh	Affiliations	ImgFileName	Description	happyHour	Links
Keynote	Herren Wu		Senior Vice President and Head of Antibody Discovery and Protein Engineering (ADPE), R&D at AstraZeneca	Keynote_Wu_Herren.jpg	<p>Dr. Wu has about 28-year experience in biological drug discovery and development. He started as Director to build the Department of Antibody Discovery and Protein Engineering in MedImmune in 2002. He was promoted to Senior Director in 2004, Vice President in 2006 and SVP, Chief Technology Officer in 2016. After MedImmune was integrated into AstraZeneca, he was appointed SVP, R&D, AstraZeneca in January 2019. Prior to joining MedImmune/AstraZeneca, he served at leadership roles at Tanox, Inc. (acquired by Genentech in 2007) and Applied Molecular Evolution, Inc. (now a subsidiary of Eli Lilly & Co.). He is the recipient of the Senior Technology Fellow Emerald Honors award in 2006. He is also an inventor on 50 granted US patents. He has 110 peer-reviewed publications.</p><p>Dr. Wu received his bachelorâ€™s degree (1986) in Chemistry from the National Taiwan University and his doctorate (1993) in Molecular and Cellular Biology from the University of Massachusetts, Amherst. He completed his postdoctoral training (1995) at The Scripps Research Institute in La Jolla, California.</p>	Yes/No	https://www.astrazeneca.com/our-company/our-people/herren-wu.html
Keynote	Jeannie Lee		Professor of Genetics (and Pathology) at Harvard Medical School and Vice Chair of Molecular Biology at the Massachusetts General Hospital	Keynote_JeannieLee.jpeg	<p>Dr. Jeannie T. Lee is a Professor of Genetics (and Pathology) at Harvard Medical School and Vice Chair of Molecular Biology at the Massachusetts General Hospital. Dr. Lee specializes in the study of epigenetic regulation by long noncoding RNAs and uses X-chromosome inactivation as a model system. She is a Member of the National Academy of Sciences, a 2018 Harrington Rare Disease Scholar of the Harrington Discovery Institute, the 2016 recipient of the Lurie Prize from the Foundation for the National Institutes of Health, a 2016 awardee of the Centennial Prize from the Genetics Society of America, a recipient of the Molecular Biology Prize (2010) and the Cozzarelli Prize (2020) from the National Academy of Sciences, U.S.A, and a Fellow of the American Association for the Advancement of Science. Dr. Lee was also named a Distinguished Graduate of the University of Pennsylvania School of Medicine in 2013 and an Investigator of the Howard Hughes Medical Institute. From 2013-2018, she co-launched the Epigenetics Initiative at Harvard Medical School and served as its Co-Director. Serving on the Board of Directors of the Genetics Society of America (GSA), Dr. Lee spearheaded the TAGC (The All-Genetics) Conference in 2016. As GSA's President, Dr. Lee established a Strategic Plan and a Development strategy for the society in 2018. She received her A.B. in Biochemistry and Molecular Biology from Harvard University and obtained M.D.-Ph.D degrees from the University of Pennsylvania School of Medicine. Dr. Lee then carried out postdoctoral work at the Whitehead Institute & MIT and became Chief Resident of Clinical Pathology at the Massachusetts General Hospital prior to joining the Faculty at Harvard Medical School. As a new investigator, she received the Basil Oâ€™Connor Scholar Award from the March of Dimes and the Pew Scholars Award. As a champion of translational science, she played a major role in the founding of Translate Bio and Fulcrum Therapeutics. Basic mechanisms in X chromosome inactivation are being translated to better understand and treat Rett Syndrome, Fragile X Synconfirmingdrome, autism-spectrum disorders, and other X-linked disorders.</p>	Yes/No	https://www.linkedin.com/in/jeannie-t-lee-1a3571b/
Academia to Industry I	Gautam Rajpal		Managing Patner at The SearchLite	Academia_GR.jpg		Yes/No	https://www.linkedin.com/in/gautamrajpal/
Academia to Industry I	Jeremy Chang		Senior Associate, Asset Acquisition at BridgeBio	Jeremy_Chang.jpg		Yes/No	https://www.linkedin.com/in/jeremy-chang-986208b/
Academia to Industry I	Ying-Li Chen		Senior Manager, Business Development and Strategic Marketing at Stanford Office of Technology Licensing	Academia_Ying-Li_Chen.jpg		Yes/No	https://www.linkedin.com/in/ying-li-chen-mba-b400621a/
Trending Topic I	Sengwee Darren Toh		Professor at Harvard Medical School & HSPH and Associate Director, TIDE, Sentinel Center, Harvard Pilgrim	Trending_Darren_Toh.jpg	<p>Darren Toh, ScD is Professor in the Department of Population Medicine at Harvard Medical School and Harvard Pilgrim Health Care Institute, and Professor in the Department of Epidemiology at Harvard T.H. Chan School of Public Health. He is a pharmacoepidemiologist with an interest in the real-world comparative safety and effectiveness research of medical products. His research focuses on 1) assessing the risks and benefits of medical products using real-world data collected as part of routine healthcare delivery, and 2) developing and applying privacy-protecting analytic methods to conduct multi-center studies in distributed data networks. Darren is Chief Scientist at the Operations Center of the FDA-funded Sentinel System, a congressionally mandated national medical product safety surveillance program. He received his doctoral degree in Epidemiology from the Harvard School of Public Health.</p>	Yes/No	https://www.linkedin.com/in/sengweetoh/
Trending Topic I	Lina Titievsky		Senior Director, Global RWE COE at Vertex Pharmaceuticals	Trending_Lina_Titievsky.jpg	<p>Lina Titievsky, PhD MPH is a Senior Director in Real World Evidence (RWE) at Vertex. In this role, she manages a team responsible for RWE activities in the General Medicine disease areas, including hemoglobinopathy, kidney and diabetes. Lina began her career as an epidemiologist at Pfizer in 2005 where she served as a lead epidemiologist for numerous products across several therapeutic areas, including vaccines, rare diseases and oncology with a primary focus on the regulatory and safety strategy and benefit/risk management. Immediately prior to Vertex, Lina spent 2 years at Intercept, a non-viral liver disease company, where was the Head of Medical Affairs Research and managed a team responsible for generating RWE for Primary Biliary Cholangitis and Nonalcoholic Steatohepatitis to address various stakeholders’ needs including regulatory authorities and payers.  Lina is an active member of International Society for Pharmacoepidemiology and previously served as the Chair of the Pediatric Special Interest Group.  Lina holds a PhD in epidemiology from Columbia University.</p>	Yes/No	https://www.linkedin.com/in/lina-titievsky-55937210/
Trending Topic I	Liz Garry		Senior Principal Scientist at Aetion	Trending_LizGarry.JPG		Yes/No	https://www.linkedin.com/in/liz-garry-phd-mph-6626b8161/
Trending Topic II	Tasuku Kitada		Co-founder, Director, President, and Head of R&D at Strand Therapeutics	Tasuku-Kitada.jpg	<p>Tasuku Kitada is President and Head of R&D of Strand Therapeutics. He co-founded Strand and serves on its Board of Directors. Prior to Strand, Tasuku was Senior Biotechnology Analyst at Candriam Investors Group, where he conducted due diligence for the company’s multi-billion-dollar biopharma public equity investment strategy. At Candriam, he focused on cell and gene therapy companies, and also covered numerous oncology companies. Currently, Tasuku continues to serve Candriam Investors Group as an advisor. Prior to Candriam, Tasuku was a researcher at the Synthetic Biology Center at Massachusetts Institute of Technology where he became the first scientist to create synthetic gene circuits using synthetic mRNA. This was the first demonstration of post-transcriptional circuits that can be “wired” to create a variety of networks of increasing complexity, which enabled cell type specific expression as well as small-molecule based control of gene expression from synthetic mRNA. This important research led to publications in Science, Nature Biotechnology, and Nature Chemical Biology. The mRNA synthetic biology platform developed from this research has been exclusively licensed to Strand. Tasuku holds a Ph.D. in Molecular Biology from University of California, Los Angeles and a B.S. in Biophysics and Biochemistry from University of Tokyo.</p>	Yes/No	https://www.linkedin.com/in/tasukukitada/
Trending Topic II	Allen Horhota		Director, Head of Delivery at Orna Therapeutics, Inc.	Allen-Horhota.jpg		Yes/No	https://www.linkedin.com/in/allen-horhota-22a1219/
Trending Topic II	Ho-Chou Tu		Associate Director at Alnylam Pharmaceuticals	Ho-Chou-Tu.jpg	<p>Ho-Chou holds a PhD in Molecular and Cell Biology from Washington University in St. Louis, where she studied the various cell death mechanisms in normal and cancer cells. Her post-doctoral training was done at Boston Children’s Hospital/Harvard Medical School, where she focused on investigating the roles of stem cell factors in solid tumor development and progression. In 2015, she joined Alnylam Pharmaceuticals, the leading biotech developing a world-class platform of RNAi therapeutics. In 2018, Alnylam received the first-ever RNAi therapeutics approval by the FDA and currently has 4 commercial and 10+ clinical-stage programs in the pipeline. Ho-Chou leads a multidisciplinary team in the “Next Wave” Liver group with the mission to fuel and expand the future Alnylam liver pipeline. She also serves as research lead in several pre-clinical and clinical-stage programs, focusing on NASH, cardiometabolic, and rare genetic diseases.</p>	Yes/No	https://www.linkedin.com/in/ho-chou-tu/
Academia to Industry II	Ariel (Wei-His) Yeh		Scientist, a gene editing startup	Academia_Ariel.jpg	<p>With a background in biomolecular research training from Prof. David Liu, Dr. Yeh’s doctoral research focused on making base editors, a precision genome editing technology, clinically relevant by developing delivery technologies and demonstrating their ability to correct a single genetic mutation in mouse models. In collaboration with clinical researchers and genetic engineering experts, Dr. Yeh developed the first gene correction approach for restoring auditory function in a mouse model of congenital deafness. Her patents on genome editing have been licensed by startups and she has published more than 10 peer-reviewed papers, two of which are first-authored. Her research has been published in top journals, including Nature Communications, Science Translational Medicine, and Nature Biomedical Engineering. Her work has been featured in various outlets, including Research Highlights by Nature Reviews, The Harvard Gazette, and ScienceDaily. After graduation, Dr. Yeh began her career as one of the first scientists at Prime Medicine. As she continues her path in therapeutics, she is selected by expert Healthcare judges into the 2021 class of Forbes 30 under 30, the world’s most impactful community of young entrepreneurs and game-changers. </p>	Yes/No	https://www.linkedin.com/in/ariel-wei-hsi-yeh-90065a94/
Academia to Industry II	Yi-Li Min		Scientist II, Preclinical development, Vertex Pharmaceuticals	Academia_Yi-Li_Min.jpg		Yes/No	https://www.linkedin.com/in/yilimin/
Networking - Clinical Research	Szu-Ta Chen		Associate Medical Director & Global Clinical Lead, Clinical Science, GI TAU, Takeda
Networking - Clinical Research	Hsiao-Ling Hung		Vice President, Head of Regulatory Affairs & Quality Assurance at Ambrx	Networking_Hsiao-Ling_Hung.jpg		Yes/No	https://www.linkedin.com/in/hsiao-ling-hung-phd-rac-7771113/
Networking - Clinical Research	Allen Chia-En Lien		Director at Medigen Vaccine Biologics Corp	Chia-En-Lien.jpg		Yes/No	https://www.linkedin.com/in/allen-chia-en-lien-m-d-drph-1670b721/
Networking - Clinical Research	Dajun Sun		Senior Scientist at The Janssen Pharmaceutical Companies of Johnson & Johnson	Networking_Dajun_Sun.jpg		Yes/No	https://www.linkedin.com/in/dajunsun/
Networking - Clinical Research	Rosa Wang		Associate Director, Global HEOR	Networking_Rosa_Wang.jpg		Yes/No	https://www.linkedin.com/in/rosa-wang-5aa2a125/
Networking - Clinical Research	Margaret Wey		Senior Medical Scientist, Global Medicines Development, AstraZeneca	Networking_Margaret_Wey.jpg	Yes/No	https://www.linkedin.com/in/margaretwey/
Networking - Start-ups & VC	Shaoyu Chang 		Associate Director, Innovation and Educational Research, Vertex Pharmaceuticals	Networking_Shaoyu_Chang.jpg	<p>Shaoyu joined Vertex as Innovation and Educational Research (VIER) Associate Director in September 2020. The VIER team builds and supports communities of innovators throughout the organization to generate new, value-adding solutions to organizational needs. Shaoyu brings in 3-year experience in venture capital with FC Capital and VI Ventures, both cross-border VC funds specializing in early-stage biotech opportunities. Shaoyu took an active leadership role in the full life cycle of investment, from origination to evaluation, execution, and post-investment management. Prior to that, Shaoyu gained consulting experience as Director of Investor Research at Life Science Nation, specializing in US-Asia transactions. Shaoyu began his career as Research Scholar in global health and technology access at Sanford School of Public Policy at Duke University. Shaoyu received a Master of Public Health (MPH) from Harvard T.H. Chan School of Public Health and M.D. from National Taiwan University. Additionally, Shaoyu is US Regulatory Affairs Certified (RAC) with robust knowledge in clinical trials and pharmaceutical development. </p>	Yes/No	https://www.linkedin.com/in/shaoyuchang/
Networking - Start-ups & VC	Ming-Kuei Jang 		Co-Founder and CEO at APRINOIA Therapeutics
Networking - Start-ups & VC	Yi-Kai Lo		CEO at Niche Biomedical Inc.	Yi-Kai-Lo.jpg		Yes/No	https://www.linkedin.com/in/yi-kai-lo-53531977/
Networking - Start-ups & VC	Ting-Hui Wu		Consultant at McKinsey & Company	Ting-Hui-Wu.jpg		Yes/No	https://www.linkedin.com/in/ting-hui-wu-md-msc-ab535733/
Networking - Academia	Erica Cai		Assistant Investigator at the Indiana Biosciences Research Institute Diabetes Center
Networking - Academia	Chia-Wei Cheng		Assistant Professor at Columbia University Irving Medical Center	Chia-Wei-Cheng.jpg	<p>Dr. Cheng conducted her doctoral research in Dr. Valter D. Longo’s laboratory at University of Southern California (USC). She moved to Boston during her postdoctoral training in Dr. Omer H. Yilmaz’s laboratory at Koch Institute at Massachusetts Institute of Technology (MIT). Dr. Cheng was a fellow of Helen Hay Whitney Foundation (HHWF) and awardee of the NIH Pathway to Independence Award (K99), with Dr. David M. Sabatini's co-mentorship. Earlier this year, Dr. Cheng joined Columbia University Irving Medical Center (CUIMC), Department of Genetics and Development (G&D) and Columbia Stem Cell Initiative (CSCI), as an assistant professor. Her Lab studies the molecular machinery translating nutritional cues into cell fate decision.  Her goal is to decipher the nutrigenomic underpinning of stem cell identity, in the hopes of inspiring new therapeutic strategies.</p>	Yes/No	https://www.linkedin.com/in/chia-wei-cheng-6103771a/
Networking - Academia	Meng-Chuan Lai		Assistant Professor at University of Toronto; Clinician Scientist at Centre for Addiction and Mental Health	Meng-Chuan-Lai.jpg		Yes/No	https://www.linkedin.com/in/meng-chuan-lai-5b3423101/
Networking - Academia	Sheng Chih (Peter) Jin		Assistant Professor of Genetics at Washington University School of Medicine in St. Louis
Networking - Academia	Hsiao-Ying (Monica) Wey		Assistant Professor at The MGH/HST Martinos Center for Biomedical Imaging	Academia_Wey.jpg		Yes/No	https://www.linkedin.com/in/hsiao-ying-monica-wey-b677187/
Networking - Preclinical and R&D	Shian-Huey Chiang		Director, Head of Emerging Science Biology, Target Sciences, ES&I, Pfizer Inc.	Networking_Shian-Huey_Chiang.jpg		Yes/No	https://www.linkedin.com/in/shianhueychiang/
Networking - Preclinical and R&D	Meredith Kuo		Scientist at Calithera Biosciences	Meredith-Kuo.jpg		Yes/No	https://www.linkedin.com/in/meredith-szu-yu-kuo/
Networking - Preclinical and R&D	Richard Liang		Biomarker Scientist, Denali Therapeutics
Networking - Preclinical and R&D	Yvonne Meng		Principal Scientist, Biologics Discovery, Janssen Biotherapeutics (JBIO) at Johnson & Johnson
Networking - AI & Machine Learning 	Pin-Kuan Lai		Incoming Assistant Professor, Stevens Institute of Technology
Networking - AI & Machine Learning 	Ching-Yung Lin		CEO, Graphen Inc.	Chin-Yung-Lin.jpg		Yes/No	https://www.linkedin.com/in/ching-yung-lin-97b640/
Networking - AI & Machine Learning 	Michael Shih		Data Scientist at GNF of Novartis Institutes for BioMedical Research (NIBR)	Michael-Shih.jpg		Yes/No	https://www.linkedin.com/in/michaelcshih/			`;

const tsv_array = tsv_str
	.split('\n')
	.map(el => el.split('\t'))
	.filter(el => el[1])
	.map(el => {
		return {
			'name': el[1].trim() || null,
			'nameCh': el[2] || null,
			'affiliations': el[3] ? el[3].split(';') : [],
			'imgFileName': el[4] || 'placeholder.jpg',
			'links': el[7] ? el[7].split(';') : [],
			'description': el[5] || ''
		};
	});

const tsv_dict = {};

tsv_array.forEach(el => {
	el.name.trim() in Object.keys(tsv_dict)
		? false
		:  tsv_dict[el.name.trim()] = el;
});

export const speakersObj = tsv_dict;
